spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: cyb123456
          url: jdbc:mysql://127.0.0.1:3306/students?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
#        history:
#          url: jdbc:mysql://10.32.22.222:9030/flink?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#          username: root
#          password:
#          driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package : com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
